### ISSUE TITLE
Invalid selection from Operational Mode step6

### ISSUE THREAD

**Issue by gisunkim** [ibm-mas/installer#557] opened 2023-10-16 01:25 UTC
Cannot install MAS using 7.4.1 cli.
Getting error doesn't matter to what is selected

Select Operational Mode > 2
Invalid Selection

Fatal Error[1]  See /opt/app-root/src/.ibm-mas/logs/mas.log for details

**Comment by mattlrx** [comment] 2023-10-16 06:55
this error occurs when installing 8.9.9 (catalog entry 4) but not with 8.11.0 or 8.10  
  
the content of the log mentioned in the error is:  
Connected to OCP cluster:   
  ^\[\[36m^\[\[4mhttps://console-openshift-console.apps.elm-support-ocp.os.fyre.ibm.com^\[(B^\[\[m^\[(B^\[\[m   
subscription.operators.coreos.com/openshift-pipelines-operator unchanged   
NAME               CREATED AT   
tasks.tekton.dev   2023-03-07T16:12:46Z   
Wait for Pipeline operator to be ready   
customresourcedefinition.apiextensions.k8s.io/tasks.tekton.dev condition met   
Wait for Tekton config to be available   
NAME     VERSION   READY   REASON   
config   1.8.2     True   
Patch Tekton config to enable alpha API fields and scope when expressions to tasks   
tektonconfig.operator.tekton.dev/config patched (no change)   
Set the default pipeline tasks timeout to 12 hours   
configmap/config-defaults patched (no change)

![](https://github.com/ibm-mas/cli/assets/32359792/f914309f-d5ec-4698-8188-7a40c1c65e60)

**Comment by mattlrx** [comment] 2023-10-16 07:02
this error occurs when installing 8.9.9 (catalog entry 4) but not with 8.11.0 or 8.10

Steps to reproduce:

lanch the install through the cli:

mas install

in step 3 choose catalog entry 4 (8.9.9)

in step 6, select operational mode 1 or 2 (doesn't matter)

expected result:  
get to step 7

Actual Result:  
error message:  
Invalid Selection   
  
Fatal Error\[1\]  See /opt/app-root/src/.ibm-mas/logs/mas.log for details  
  
 

additional information:  
the content of the related log file :  
  
Connected to OCP cluster:   
  ^\[\[36m^\[\[4mhttps://console-openshift-console.apps.elm-support-ocp.os.fyre.ibm.com^\[(B^\[\[m^\[(B^\[\[m   
subscription.operators.coreos.com/openshift-pipelines-operator unchanged   
NAME               CREATED AT   
tasks.tekton.dev   2023-03-07T16:12:46Z   
Wait for Pipeline operator to be ready   
customresourcedefinition.apiextensions.k8s.io/tasks.tekton.dev condition met   
Wait for Tekton config to be available   
NAME     VERSION   READY   REASON   
config   1.8.2     True   
Patch Tekton config to enable alpha API fields and scope when expressions to tasks   
tektonconfig.operator.tekton.dev/config patched (no change)   
Set the default pipeline tasks timeout to 12 hours   
configmap/config-defaults patched (no change)

![](https://github.com/ibm-mas/cli/assets/32359792/f914309f-d5ec-4698-8188-7a40c1c65e60)

**Comment by andrercm** [comment] 2023-10-19 18:38
@mattlrx @gisunkim I could not reproduce this issue with latest cli version (7.4.4).

![image](https://github.com/ibm-mas/cli/assets/31037381/f2da1560-1a90-4a9f-85cb-0631fd43be67)

Can you please try again with latest cli version and let us know the output?

In case it still fails for you, would you also share the output for the following command:

```
cat /opt/app-root/src/.ibm-mas/logs/mas.log
```

Thank you!

**Comment by durera** [comment] 2023-10-19 20:35
This has indeed been fixed in https://github.com/ibm-mas/cli/pull/558

**Closed as completed by durera** 2023-10-19 20:35 UTC
Labels: Bug Report, Triage
