### ISSUE TITLE
Deprovision should force a must gather

### ISSUE THREAD

**Issue by IanBoden** [ibm-mas/installer#503] opened 2023-09-19 08:39 UTC
The deprovision task waits for a pipeline to complete with the intention that the pipeline will run a must gather to collect all relevant information prior to it finishing. However, if the must gather fails or the upload of it fails the pipeline will complete and the deprovision will delete all evidence that anything went wrong.

The deprovision should:

- Check that a must gather has been uploaded
- If a must gather has not been uploaded trigger a new one
- Repeat until a must gather has been uploaded or manual intervention

essentially we need to add a wait for must gather step after:
https://github.com/ibm-mas/cli/blob/4bcdf9e815701831bc47b37b5231a72f231fe46c/tekton/src/pipelines/fvt-deprovision-after.yml.j2#L36

**Comment by durera** [comment] 2023-12-01 18:02
Duplicate of #476 really ... `must-gather` needs to be robust that we can rely on it. Through various enhancements it's better able to handle errors now.

**Closed as completed by durera** 2023-12-01 18:02 UTC
Labels: Bug Report
